type Product = {
  product_name: string;
  product_category: string;
  product_price: number;
  image: string;
  quantity: number;
  description: string;
};

export const products: Product[] = [
  {
    product_name: "Wireless Headphones",
    product_category: "Electronics",
    product_price: 59.99,
    image: "./images/1.png",
    quantity: 100,
    description: "High-quality wireless headphones with noise cancellation.",
  },
  {
    product_name: "Smartphone Case",
    product_category: "Accessories",
    product_price: 12.99,
    image: "./images/2.png",
    quantity: 200,
    description: "Durable and stylish case for smartphones.",
  },
  {
    product_name: "Laptop Stand",
    product_category: "Office Supplies",
    product_price: 25.99,
    image: "./images/4.png",
    quantity: 50,
    description: "Adjustable aluminum laptop stand for better ergonomics.",
  },
  {
    product_name: "Mechanical Keyboard",
    product_category: "Electronics",
    product_price: 79.99,
    image: "./images/5.png",
    quantity: 80,
    description: "RGB mechanical keyboard with customizable keys.",
  },
  {
    product_name: "Gaming Mouse",
    product_category: "Electronics",
    product_price: 34.99,
    image: "./images/6.png",
    quantity: 120,
    description: "Ergonomic gaming mouse with high DPI sensor.",
  },
  {
    product_name: "USB-C Hub",
    product_category: "Accessories",
    product_price: 49.99,
    image: "./images/7.png",
    quantity: 75,
    description: "Multi-port USB-C hub with HDMI and USB 3.0.",
  },
  {
    product_name: "Bluetooth Speaker",
    product_category: "Electronics",
    product_price: 45.99,
    image: "./images/8.png",
    quantity: 90,
    description: "Portable Bluetooth speaker with deep bass.",
  },
  {
    product_name: "Fitness Tracker",
    product_category: "Wearables",
    product_price: 39.99,
    image: "./images/9.png",
    quantity: 60,
    description: "Smart fitness tracker with heart rate monitoring.",
  },
  {
    product_name: "LED Desk Lamp",
    product_category: "Home & Office",
    product_price: 29.99,
    image: "./images/10.png",
    quantity: 150,
    description: "Adjustable LED desk lamp with multiple brightness levels.",
  },
  {
    product_name: "Smartwatch",
    product_category: "Wearables",
    product_price: 99.99,
    image: "./images/3.png",
    quantity: 85,
    description: "Feature-rich smartwatch with fitness tracking.",
  },
  {
    product_name: "Power Bank",
    product_category: "Accessories",
    product_price: 27.99,
    image: "./images/7.png",
    quantity: 110,
    description: "10,000mAh power bank for charging on the go.",
  },
  {
    product_name: "Electric Kettle",
    product_category: "Home Appliances",
    product_price: 39.99,
    image: "./images/8.png",
    quantity: 95,
    description: "Fast-boiling electric kettle with auto shut-off.",
  },
  {
    product_name: "Air Purifier",
    product_category: "Home Appliances",
    product_price: 129.99,
    image: "./images/1.png",
    quantity: 45,
    description: "HEPA filter air purifier for clean indoor air.",
  },
  {
    product_name: "Wireless Earbuds",
    product_category: "Electronics",
    product_price: 49.99,
    image: "./images/2.png",
    quantity: 130,
    description: "True wireless earbuds with noise isolation.",
  },
  {
    product_name: "Digital Thermometer",
    product_category: "Health & Wellness",
    product_price: 14.99,
    image: "./images/3.png",
    quantity: 180,
    description: "Fast and accurate digital thermometer for all ages.",
  },
  {
    product_name: "Smart Light Bulb",
    product_category: "Home Automation",
    product_price: 22.99,
    image: "./images/4.png",
    quantity: 160,
    description: "Color-changing smart light bulb with voice control.",
  },
  {
    product_name: "Electric Toothbrush",
    product_category: "Health & Wellness",
    product_price: 59.99,
    image: "./images/5.png",
    quantity: 70,
    description: "Rechargeable electric toothbrush with multiple modes.",
  },
  {
    product_name: "Portable Blender",
    product_category: "Kitchen Appliances",
    product_price: 34.99,
    image: "./images/6.png",
    quantity: 100,
    description: "Compact blender for smoothies and shakes.",
  },
  {
    product_name: "Smart Door Lock",
    product_category: "Home Security",
    product_price: 149.99,
    image: "./images/7.png",
    quantity: 40,
    description: "Keyless smart door lock with fingerprint access.",
  },
  {
    product_name: "Noise-Canceling Headphones",
    product_category: "Electronics",
    product_price: 199.99,
    image: "./images/9.png",
    quantity: 55,
    description: "Premium noise-canceling headphones for immersive sound.",
  },
];
